name: Beastly Torrent Transporter
on:
  workflow_dispatch:
    inputs:
      torrent_url:
        description: 'Direct Link to .torrent file or Magnet Link'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
          pip install pyrogram tgcrypto

      - name: Download Torrent
        run: |
          # aria2c downloads the torrent content into a folder named 'downloads'
          aria2c --seed-time=0 --dir=./downloads "${{ github.event.inputs.torrent_url }}"

            - name: Download Torrent
        run: |
          # We add '|| true' so even if aria2c times out or errors, 
          # the script moves to the next step.
          # Also adding a timeout of 10 minutes so it doesn't wait forever.
          timeout 600 aria2c --seed-time=0 --dir=./downloads "${{ github.event.inputs.torrent_url }}" || true
